services:
    spark-master: 
        container_name: spark-master
        image: apache/spark:latest
        ports:
            - "9090:8080"
            - "7077:7077"
        volumes:
            - ./apps/appMaster:/opt/spark-apps
            - ./datas/dataMaster:/opt/spark-data
            - .logs/master:/opt/spark/logs
        environment:
            - SPARK_WORKLOAD=master
        entrypoint: /bin/bash
        command: ['/opt/spark/bin/spark-class', 'org.apache.spark.deploy.master.Master']

    spark-worker-1:
        container_name: spark-worker-1
        image: apache/spark:latest
        ports:
            - "9091:8081"
        depends_on:
            - spark-master
        environment:
            - SPARK_WORKLOAD=worker
            - SPARK_MASTER=spark://spark-master:7077
            # - SPARK_WORKER_CORES=1
            # - SPARK_WORKER_MEMORY=1G
            # - SPARK_DRIVER_MEMORY=1G
            # - SPARK_EXECUTOR_MEMORY=1G
            # - SPARK_LOCAL_IP=spark-worker-1
        volumes:
            - ./apps/appWorker1:/opt/spark-apps
            - ./datas/dataWorker1:/opt/spark-data
            - .logs/worker1:/opt/spark/logs
        command: ['/opt/spark/bin/spark-class', 'org.apache.spark.deploy.worker.Worker', 'spark://spark-master:7077']

    spark-worker-2:
        container_name: spark-worker-2
        image: apache/spark:latest
        ports:
            - "9092:8081"
        depends_on:
            - spark-master
        environment:
            - SPARK_WORKLOAD=worker
            - SPARK_MASTER=spark://spark-master:7077
            # - SPARK_WORKER_CORES=1
            # - SPARK_WORKER_MEMORY=1G
            # - SPARK_DRIVER_MEMORY=1G
            # - SPARK_EXECUTOR_MEMORY=1G
            # - SPARK_LOCAL_IP=spark-worker-2
        volumes:
            - ./apps/appWorker2:/opt/spark-apps
            - ./datas/dataWorker2:/opt/spark-data
            - .logs/worker2:/opt/spark/logs
        command: ['/opt/spark/bin/spark-class', 'org.apache.spark.deploy.worker.Worker', 'spark://spark-master:7077']
